name: Trick Library Dependencies

# For more info and troubleshooting help for this workflow, see the Continuous Integration
# page in the GUNNS Wiki.
#
# We'd rather use a pre-built Docker image with the dependencies already installed, but we
# don't have a place to store the image.  We can't use the GiHhub Container Registry or
# Package containers, and don't want to use Docker Hub, so we have to configure the
# container from scratch each time.

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'bin/utils/simbus_icd_input_gen/**'
    - 'draw/**'
    - '.github/workflows/**'
    - '!.github/workflows/lib_deps.yml'

jobs:
  lib_deps:
    runs-on: ubuntu-latest
    container: docker://centos:7

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Add yum repo
      run: yum -y install epel-release.noarch && yum -y update

    - name: Install dependencies
      # Note most of these are for Trick
      run: >
        yum install -y bison clang-devel cmake curl-devel flex gcc gcc-c++ git glibc-devel gtest-devel
        java-1.8.0-openjdk-devel libX11-devel libxml2-devel libXi-devel libXmu-devel libXt-devel
        llvm-devel llvm-static make tcsh csh mesa-libGL-devel mesa-libGLU-devel maven cppunit ncurses-devel
        openmotif-devel perl-Digest-MD5 protobuf-devel python-devel sqlite-devel swig systemd-devel
        udunits2-devel which zip zlib-devel tkinter

    - name: Build Trick
      # Failure here is likely due to new or changed dependencies of Trick, see above
      run: |
        export TRICK_HOME="/home/trick"
        export MAKEFLAGS=-j`nproc`
        git clone https://github.com/nasa/trick.git ${TRICK_HOME}
        cd ${TRICK_HOME}
        ./configure
        make

    # TODO use better way to define env vars globally for all steps
    - name: Build gunns/lib/trick
      run: |
        export MAKEFLAGS=-j`nproc`
        export GUNNS_TRICK_HOME="/home/trick"
        export GUNNS_HOME=`pwd`
        cd lib/trick
        make OPTS='-O2'

    - name: Run test suite, check for pass/fail
      run: |
        export TRICK_HOME="/home/trick"
        export PATH="${PATH}:${TRICK_HOME}/bin"
        export MAKEFLAGS=-j`nproc`
        export GUNNS_HOME=`pwd`
        export MS_UTILS_HOME="${GUNNS_HOME}/ms-utils"
        export TS_MODELS_HOME="${GUNNS_HOME}/gunns-ts-models"
        cd sims/SIM_class_test_compile
        python ./test_all.py
