name: Test Trick Sim

# For more info and troubleshooting help for this workflow, see the Continuous Integration
# page in the GUNNS Wiki.
#
# We'd rather use a pre-built Docker image with the dependencies already installed, but we
# don't have a place to store the image.  We can't use the GiHhub Container Registry or
# Package containers, and don't want to use Docker Hub, so we have to configure the
# container from scratch each time.

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'bin/utils/simbus_icd_input_gen/**'
    - '.github/workflows/**'
    - '!.github/workflows/sim_test.yml'

jobs:
  sim_test:
    runs-on: ubuntu-latest
    container: docker://centos:7

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Add yum repo
      run: yum -y install epel-release.noarch && yum -y update

    - name: Install dependencies
      # Note most of these are for Trick
      run: >
        yum install -y bison clang-devel cmake curl-devel flex gcc gcc-c++ git glibc-devel gtest-devel
        java-1.8.0-openjdk-devel libX11-devel libxml2-devel libXi-devel libXmu-devel libXt-devel
        llvm-devel llvm-static make tcsh csh mesa-libGL-devel mesa-libGLU-devel maven cppunit ncurses-devel
        openmotif-devel perl-Digest-MD5 protobuf-devel python-devel sqlite-devel swig systemd-devel
        udunits2-devel which zip zlib-devel tkinter

    - name: Build Trick
      # Failure here is likely due to new or changed dependencies of Trick, see above
      run: |
        export TRICK_HOME="/home/trick"
        export MAKEFLAGS=-j`nproc`
        git clone https://github.com/nasa/trick.git ${TRICK_HOME}
        cd ${TRICK_HOME}
        ./configure
        make

    # TODO use better way to define env vars globally for all steps
    - name: Build sim
      run: |
        export TRICK_HOME="/home/trick"
        export MAKEFLAGS=-j`nproc`
        export GUNNS_HOME=`pwd`
        export MS_UTILS_HOME="${GUNNS_HOME}/ms-utils"
        export TS_MODELS_HOME="${GUNNS_HOME}/gunns-ts-models"
        export HS_CONFIG_PATH="${GUNNS_HOME}/sims/Modified_data"
        cd sims/SIM_test
        ${TRICK_HOME}/bin/trick-CP

    - name: Run sim
      run: |
        export TRICK_HOME="/home/trick"
        export MAKEFLAGS=-j`nproc`
        export GUNNS_HOME=`pwd`
        export MS_UTILS_HOME="${GUNNS_HOME}/ms-utils"
        export TS_MODELS_HOME="${GUNNS_HOME}/gunns-ts-models"
        export HS_CONFIG_PATH="${GUNNS_HOME}/sims/Modified_data"
        cd sims/SIM_test
        ./S_main* RUN_test/input_int_test.py

    - name: Check sim outputs for pass/fail
      run: |
        export GUNNS_HOME=`pwd`
        cd test/CI
        chmod +x sim_test.py
        python ./sim_test.py
